### ISSUE TITLE
Lua pattern too powerful

### ISSUE THREAD

**Issue by Ayplow** [tts-community/moonsharp-tts-debug#2]
I dont know if anything really needs to be done about this, but it will make for some nasty surprises on mod release if we're not careful - 

```lua
([['
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX']]):match "'.-'"
``` 
in the official game, this code errors with 'pattern too complex'. It looks like it cant handle a capture longer than 200 characters.  If its used in parsing any information, this could be a big problem in testing games

**Comment by Benjamin-Dobell** [comment]
Thanks for pointing this out!

I'd mentioned the possibility of something like this happening on Discord, but this is a solid example!

@TomSputz, you probably already know, but for anyone else who stumbles across this issue...

This is happening because we're using a newer version on MoonSharp than ships with TTS. In this case the newer version of MoonSharp seems to have fixed 'pattern too complex' error. Ideally we'd use the same version of MoonSharp as TTS (so that MoonSharp bugs are consistent), however the VSCode debugging stuff we're reliant on wasn't added until a newer release of MoonSharp.

Ideally we'll be able to convince Berserk Games to upgrade to the latest MoonSharp release (we can use bugs like this as motivation for them to do so), alternatively I may need to look into back porting everything, which I'd really rather avoid as it's not just my work, it's all the upstream MoonSharp stuff as well.

**Comment by Benjamin-Dobell** [comment]
TTS is now running MoonSharp 2.0.0. So this should no longer be an issue.
