### ISSUE TITLE
Wrong launch.json file

### ISSUE THREAD

**Issue by Wyko** [tts-community/moonsharp-tts-debug#4]
The launch.json file needs to be:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "MoonSharp Attach",
            "type": "moonsharp-debug",
            "debugServer": 41912,
            "request": "attach"
        }
    ]
}
```

Rather than the specified:
```
{
    "version": "0.2.0",
    "debugServer" : 41912,
    "configurations": [
        {
            "name": "MoonSharp Attach",
            "type": "moonsharp-debug",
            "request": "attach",
            "HELP": "Please set 'debugServer':41912 (or whatever port you ar connecting to) right after the 'version' field in this json."
        }
    ]
}
```

Without this change vscode errors out.

**Comment by Benjamin-Dobell** [comment]
There's nothing inherently TTS-specific about the MoonSharp VSCode plugin in this repository. MoonSharp can listen on any port, which is why the VSCode plugin doesn't hard-code the port 41912, but rather explicitly tells you to set the port (from your excerpt above):

> "HELP": "Please set 'debugServer':41912 (or whatever port you ar connecting to) right after the 'version' field in this json."

Only the MoonSharp DLL in this repository includes modifications to specifically enable TTS debugging though. That said, I intend to remove anything TTS specific and officially these debugging updates upstream into MoonSharp. Then _ideally_ add this as official functionality within TTS, so you don't need to patch TTS at all.

**Comment by marcpawl** [comment]
+1 I needed the configuration above

**Comment by mikerieser** [comment]
This should be in the README.md. 

I had encountered the Marco Masteropaolo extension:
https://marketplace.visualstudio.com/items?itemName=xanathar.moonsharp-debug

It still suggests the "wrong" launch.json.
